apiVersion: apps/v1
kind: Deployment
metadata:
  name: task5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task5
  template:
    metadata:
      labels:
        app: task5
    spec:
      containers:
        - name: task5
          image: kaveenaj/sit323-737-2023-t1-prac7p
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "5000"
